const BRAND_IMAGE =
  "https://images.unsplash.com/photo-1611930021559-4a5cb5c38da3?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D";


export const rows = [
    { brand: "Fair Bets", industry: "D2C", year: "2024", image: BRAND_IMAGE },
    { brand: "Freshen Go", industry: "FMCG", year: "2021", image: BRAND_IMAGE },
    { brand: "Maasika", industry: "FemTech", year: "2020", image: BRAND_IMAGE },
    { brand: "Naaz Bijouteries", industry: "Jewellery", year: "2020", image: BRAND_IMAGE },
    { brand: "Parzaan Dastur", industry: "Personal Brand", year: "2020", image: BRAND_IMAGE },
    { brand: "Ovenly Patisserie", industry: "Bakery", year: "2021", image: BRAND_IMAGE },
    { brand: "Zota Healthcare", industry: "Healthcare", year: "2021", image: BRAND_IMAGE },
    { brand: "Zariya India", industry: "Fashion / Artisanal", year: "2021", image: BRAND_IMAGE },
    { brand: "Herbanize", industry: "Wellness", year: "2021", image: BRAND_IMAGE },
    { brand: "Aashim Gulati", industry: "Personal Brand", year: "2021", image: BRAND_IMAGE },
    { brand: "Ahakzai", industry: "Fashion", year: "2021", image: BRAND_IMAGE },
    { brand: "Bakuli Blu Pottery", industry: "Craft / Home", year: "2021", image: BRAND_IMAGE },
    { brand: "Bareek", industry: "Fashion / Artisanal", year: "2021", image: BRAND_IMAGE },
    { brand: "Bharat Raj (UK)", industry: "Fashion", year: "2024", image: BRAND_IMAGE },
    { brand: "Chhaya Jain", industry: "Fashion", year: "2022", image: BRAND_IMAGE },
    { brand: "Cocosoul", industry: "Beauty / FMCG", year: "2021", image: BRAND_IMAGE },
    { brand: "Divya Dutta", industry: "Personal Brand", year: "2022", image: BRAND_IMAGE },
    { brand: "Eduwiskin", industry: "Skin / Beauty", year: "2020", image: BRAND_IMAGE },
    { brand: "Florelli", industry: "Accessories", year: "2021", image: BRAND_IMAGE },
    { brand: "Forage Box", industry: "Gourmet Food", year: "2020", image: BRAND_IMAGE },
    { brand: "Gltch Studios", industry: "Design Studio", year: "2024", image: BRAND_IMAGE },
    { brand: "Gur Organic", industry: "Food", year: "2020", image: BRAND_IMAGE },
    { brand: "Harisa Studios", industry: "Fashion", year: "2020", image: BRAND_IMAGE },
    { brand: "Holi Grail Box", industry: "Gifting", year: "2021", image: BRAND_IMAGE },
    { brand: "Inaya", industry: "Fashion", year: "2022", image: BRAND_IMAGE },
    { brand: "Jadau.com", industry: "Jewellery", year: "2024", image: BRAND_IMAGE },
    { brand: "Kreeva Lifestyle", industry: "Fashion", year: "2024", image: BRAND_IMAGE },
    { brand: "Kutubooku", industry: "Publishing", year: "2025", image: BRAND_IMAGE },
    { brand: "Lätt Liv (CN)", industry: "Retail", year: "2023", image: BRAND_IMAGE },
    { brand: "Moheim (JPN)", industry: "Homeware", year: "2021", image: BRAND_IMAGE },
    { brand: "Nobo Experience", industry: "Lifestyle", year: "2024", image: BRAND_IMAGE },
    { brand: "Orca Dive Club", industry: "Experience", year: "2023", image: BRAND_IMAGE },
    { brand: "Rashi Mal", industry: "Personal Brand", year: "2022", image: BRAND_IMAGE },
    { brand: "RSG Conglomerate", industry: "Corporate", year: "2024", image: BRAND_IMAGE },
    { brand: "Santico", industry: "Food", year: "2021", image: BRAND_IMAGE },
    { brand: "Sooka Interiors (NL)", industry: "Interiors", year: "2021", image: BRAND_IMAGE },
    { brand: "Summer Solstice", industry: "Fashion", year: "2021", image: BRAND_IMAGE },
    { brand: "The Basics", industry: "Fashion", year: "2023", image: BRAND_IMAGE },
    { brand: "The Knotty Rope", industry: "Fashion", year: "2021", image: BRAND_IMAGE },
    { brand: "Waxonware", industry: "Kitchenware", year: "2021", image: BRAND_IMAGE },
    { brand: "Whitehues", industry: "Art / Photo", year: "2024", image: BRAND_IMAGE },
    { brand: "Windmill Baby", industry: "Kids Apparel", year: "2023", image: BRAND_IMAGE },
    { brand: "Anita Bakes", industry: "Bakery", year: "2022", image: BRAND_IMAGE },
    { brand: "Gaurav Gupta Fine Jewellery", industry: "Jewellery", year: "2023", image: BRAND_IMAGE },
    { brand: "Generational Capital", industry: "Finance", year: "2022", image: BRAND_IMAGE },
    { brand: "Goodrich Maritime", industry: "Maritime", year: "2025", image: BRAND_IMAGE },
    { brand: "Good Flipping Burger", industry: "F&B", year: "2022", image: BRAND_IMAGE },
    { brand: "Diaries of Nomad", industry: "Bags / Apparel", year: "2022", image: BRAND_IMAGE },
    { brand: "Fix My Tips", industry: "Beauty", year: "2020", image: BRAND_IMAGE },
    { brand: "Label Jiyani", industry: "Fashion", year: "2024", image: BRAND_IMAGE },
    { brand: "Selected Homme", industry: "Fashion", year: "2022", image: BRAND_IMAGE },
    { brand: "T-Swirl Crepe (NYC)", industry: "F&B", year: "2024", image: BRAND_IMAGE },
    { brand: "Rise & Dine", industry: "F&B", year: "2023", image: BRAND_IMAGE },
    { brand: "One Less", industry: "Sustainable D2C", year: "2023", image: BRAND_IMAGE },
    { brand: "Charagh Din", industry: "Fashion", year: "2023", image: BRAND_IMAGE },
    { brand: "Stone Shippers", industry: "Manufacturing", year: "2023", image: BRAND_IMAGE },
    { brand: "Groww", industry: "Fintech", year: "2023", image: BRAND_IMAGE },
    { brand: "FamPay", industry: "Fintech", year: "2023", image: BRAND_IMAGE },
    { brand: "Inega", industry: "Talent", year: "2023", image: BRAND_IMAGE },
    { brand: "The Pantry Mumbai", industry: "F&B", year: "2023", image: BRAND_IMAGE },
    { brand: "Varun Talwalkar", industry: "Fitness", year: "2023", image: BRAND_IMAGE },
    { brand: "Vedanta Academy", industry: "Education", year: "2023", image: BRAND_IMAGE },
    { brand: "Tripoto", industry: "Travel", year: "2023", image: BRAND_IMAGE },
    { brand: "Casa Carigar", industry: "Luxury Home Decor", year: "2024", image: BRAND_IMAGE },
    { brand: "Opulus Lights", industry: "Lighting", year: "2024", image: BRAND_IMAGE },
    { brand: "Monarch Rooftop (NYC)", industry: "Hospitality", year: "2024", image: BRAND_IMAGE },
    { brand: "Writers Qi", industry: "Education", year: "2023", image: BRAND_IMAGE },
    { brand: "Label Ritu Kumar", industry: "Luxury Fashion", year: "2024", image: BRAND_IMAGE },
    { brand: "Vedant Mahajan", industry: "Personal Brand", year: "2024", image: BRAND_IMAGE },
    { brand: "Comart", industry: "Retail", year: "2024", image: BRAND_IMAGE },
    { brand: "Kunal Anil Tanna", industry: "Fashion", year: "2024", image: BRAND_IMAGE },
    { brand: "KVAR by Design", industry: "Architecture", year: "2024", image: BRAND_IMAGE },
    { brand: "Treasures by Tiara", industry: "Jewellery", year: "2025", image: BRAND_IMAGE },
    { brand: "House of Namah", industry: "Home Decor", year: "2025", image: BRAND_IMAGE },
    { brand: "Skechers", industry: "Footwear", year: "2021", image: BRAND_IMAGE },
    { brand: "TOD's", industry: "Luxury Fashion", year: "2022", image: BRAND_IMAGE },
    { brand: "Voltas", industry: "Appliances", year: "2023", image: BRAND_IMAGE },
    { brand: "JBL", industry: "Audio", year: "2022", image: BRAND_IMAGE },
    { brand: "Pepsi", industry: "Beverage", year: "2023", image: BRAND_IMAGE },
    { brand: "Being Human", industry: "Fashion", year: "2025", image: BRAND_IMAGE },
    { brand: "Mokobara", industry: "Luggage", year: "2024", image: BRAND_IMAGE },
    { brand: "Gaurav Gupta", industry: "Couture", year: "2021", image: BRAND_IMAGE },
    { brand: "IDFC First Bank", industry: "Banking", year: "2022", image: BRAND_IMAGE },
    { brand: "Limelight Diamonds", industry: "Jewellery", year: "2025", image: BRAND_IMAGE },
    { brand: "Salman Khan Films", industry: "Entertainment", year: "2025", image: BRAND_IMAGE },
    { brand: "Rage Coffee", industry: "FMCG", year: "2023", image: BRAND_IMAGE },
    { brand: "WOW Bakery", industry: "", year: "2025", image: BRAND_IMAGE },
    { brand: "Chanchelo's", industry: "", year: "2025", image: BRAND_IMAGE },
    { brand: "WealthFusion", industry: "", year: "2025", image: BRAND_IMAGE },
    { brand: "Regeno", industry: "", year: "2025", image: BRAND_IMAGE },
    { brand: "TOVA Wellness", industry: "", year: "2025", image: BRAND_IMAGE },
    { brand: "NatureFit", industry: "", year: "2025", image: BRAND_IMAGE },
    { brand: "Shweta Tripathi Sharma", industry: "", year: "2024", image: BRAND_IMAGE },
  ];